data_validation:
  required_columns:
    - customerID
    - gender
    - SeniorCitizen
    - Partner
    - Dependents
    - tenure
    - PhoneService
    - InternetService
    - Contract
    - MonthlyCharges
    - TotalCharges
    - Churn
  max_null_percentage: 5
  expected_dtypes:
    customerID: object
    gender: object
    SeniorCitizen: int64
    tenure: int64
    MonthlyCharges: float64
    TotalCharges: object
    Churn: object
